language: ruby
bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - jruby-19mode

sudo: false  # Apparently the way to use container-based environment. Intuitive...
services: mongodb
